name: Flow for ikan automation

on:
  push:
    branches:
      - main

jobs:
  sample-ikan:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Docker build
      - name: Docker build
        run: docker build 

      - name: Docker push
        run: docker push 

      # Docker pull
      - name: Docker pull
        run: docker pull 

      # Docker run
      - name: Docker run
        run: docker run 
