name: Flow for ikan automation

on:
  push:
    branches:
      - main

jobs:
  sample-ikan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: docker build -t edoarmando/ikan:latest .

      - name: Docker push
        run: docker push edoarmando/ikan:latest

      - name: Docker pull
        run: docker pull edoarmando/ikan:latest

      - name: Docker run
        run: docker run --rm edoarmando/ikan:latest
